import { Bot, KeyRound, Pencil, Plus, Trash2, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";
import { Modal } from "../components/Modal";
import { EmptyState, Status } from "../components/Status";
import { useAuth } from "../contexts/AuthContext";
import { api, json } from "../lib/api";
import { formatDate, formatLatency } from "../lib/format";
import type { AiTargetItem, NodeItem } from "../types";

const emptyForm = { name: "", baseUrl: "", chatPath: "/v1/chat/completions", model: "", apiKey: "", prompt: "Reply with OK only.", intervalSeconds: 300, timeoutSeconds: 60, enabled: true, balanceUrl: "", balancePath: "", balanceIntervalSeconds: 1800, probeNodeIds: [] as string[] };

export function AiTargetsPage() {
  const { user } = useAuth();
  const [items, setItems] = useState<AiTargetItem[]>([]);
  const [nodes, setNodes] = useState<NodeItem[]>([]);
  const [form, setForm] = useState(emptyForm);
  const [editing, setEditing] = useState<AiTargetItem | null>(null);
  const [open, setOpen] = useState(false);
  async function load() {
    const [targets, nodeList] = await Promise.all([
      api<{ targets: AiTargetItem[] }>("/api/ai-targets"), api<{ nodes: NodeItem[] }>("/api/nodes"),
    ]);
    setItems(targets.targets); setNodes(nodeList.nodes);
  }
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30_000); return () => window.clearInterval(timer); }, []);
  function create() { setEditing(null); setForm(emptyForm); setOpen(true); }
  function edit(item: AiTargetItem) { setEditing(item); setForm({ name: item.name, baseUrl: item.baseUrl, chatPath: item.chatPath, model: item.model, apiKey: "", prompt: item.prompt, intervalSeconds: item.intervalSeconds, timeoutSeconds: item.timeoutSeconds, enabled: item.enabled, balanceUrl: item.balanceUrl ?? "", balancePath: item.balancePath ?? "", balanceIntervalSeconds: item.balanceIntervalSeconds, probeNodeIds: item.probeNodeIds }); setOpen(true); }
  async function save(event: React.FormEvent) { event.preventDefault(); const payload = { ...form, apiKey: form.apiKey || undefined }; await api(editing ? `/api/ai-targets/${editing.id}` : "/api/ai-targets", json(editing ? "PATCH" : "POST", payload)); setOpen(false); await load(); }
  async function remove(item: AiTargetItem) { if (!window.confirm(`删除上游“${item.name}”及其历史探测？`)) return; await api(`/api/ai-targets/${item.id}`, json("DELETE")); await load(); }
  return <div className="page-stack">
    <div className="page-actions"><div><span className="eyebrow">OPENAI COMPATIBLE</span><p className="page-summary">真实流式请求、首包延迟与上游余额</p></div>{user?.role === "admin" && <button className="primary-button" onClick={create}><Plus size={17} />添加上游</button>}</div>
    {items.length ? <section className="ai-grid">{items.map((item) => <article className="ai-card" key={item.id}><header><span className="ai-logo"><Bot size={20} /></span><div><strong>{item.name}</strong><span>{item.model}</span></div><Status good={Boolean(item.latest?.success)} muted={!item.enabled} label={!item.enabled ? "停用" : item.latest?.success ? "正常" : item.latest ? "异常" : "等待"} /></header><div className="ai-metrics"><div><span>流式首包</span><strong>{formatLatency(item.latest?.ttfbMs)}</strong></div><div><span>完整响应</span><strong>{formatLatency(item.latest?.totalMs)}</strong></div><div><span>账户余额</span><strong>{item.latest?.balance === null || item.latest?.balance === undefined ? "-" : item.latest.balance.toFixed(2)}</strong></div></div><div className="ai-meta"><span><KeyRound size={14} />{item.hasApiKey ? "密钥已配置" : "缺少密钥"}</span><span><WalletCards size={14} />每 {Math.round(item.intervalSeconds / 60)} 分钟</span><span>{formatDate(item.latest?.checkedAt)}</span></div>{item.latest?.error && <div className="inline-error">{item.latest.error}</div>}{user?.role === "admin" && <footer><button className="secondary-button small" onClick={() => edit(item)}><Pencil size={15} />编辑</button><button className="icon-button danger" onClick={() => void remove(item)} title="删除"><Trash2 size={16} /></button></footer>}</article>)}</section> : <section className="content-band"><EmptyState title="暂无 AI 上游" detail="添加独立低额度监控密钥后执行真实 SSE 流式探测" /></section>}
    <Modal open={open} title={editing ? "编辑 AI 上游" : "添加 AI 上游"} onClose={() => setOpen(false)} wide><form className="form-grid" onSubmit={save}><label><span>显示名称</span><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label><span>模型</span><input value={form.model} onChange={(e) => setForm({ ...form, model: e.target.value })} required /></label><label className="field-span"><span>Base URL</span><input type="url" value={form.baseUrl} onChange={(e) => setForm({ ...form, baseUrl: e.target.value })} placeholder="https://api.example.com" required /></label><label><span>Chat 路径</span><input value={form.chatPath} onChange={(e) => setForm({ ...form, chatPath: e.target.value })} required /></label><label><span>监控 API Key</span><input type="password" autoComplete="new-password" value={form.apiKey} onChange={(e) => setForm({ ...form, apiKey: e.target.value })} placeholder={editing ? "留空保持当前密钥" : "sk-..."} required={!editing} /></label><label className="field-span"><span>探测提示词</span><input value={form.prompt} onChange={(e) => setForm({ ...form, prompt: e.target.value })} required /></label><label><span>频率（秒）</span><input type="number" min="60" value={form.intervalSeconds} onChange={(e) => setForm({ ...form, intervalSeconds: Number(e.target.value) })} /></label><label><span>超时（秒）</span><input type="number" min="5" value={form.timeoutSeconds} onChange={(e) => setForm({ ...form, timeoutSeconds: Number(e.target.value) })} /></label><label className="field-span"><span>余额接口（可选）</span><input type="url" value={form.balanceUrl} onChange={(e) => setForm({ ...form, balanceUrl: e.target.value })} /></label><label><span>余额 JSON 路径</span><input value={form.balancePath} onChange={(e) => setForm({ ...form, balancePath: e.target.value })} placeholder="data.balance" /></label><label><span>余额频率（秒）</span><input type="number" min="300" value={form.balanceIntervalSeconds} onChange={(e) => setForm({ ...form, balanceIntervalSeconds: Number(e.target.value) })} /></label><div className="field-span probe-selector"><span>分布式探测节点</span><div><label className="probe-option fixed"><input type="checkbox" checked readOnly /><span>监控核心</span><small>始终启用</small></label>{nodes.map((node) => <label className="probe-option" key={node.id}><input type="checkbox" checked={form.probeNodeIds.includes(node.id)} onChange={(event) => setForm({ ...form, probeNodeIds: event.target.checked ? [...form.probeNodeIds, node.id] : form.probeNodeIds.filter((id) => id !== node.id) })} /><span>{node.name}</span><small>{node.online ? "在线" : "离线"}</small></label>)}</div></div><label className="switch-field field-span"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm({ ...form, enabled: e.target.checked })} /><span>启用真实探测</span></label><div className="modal-actions field-span"><button type="button" className="secondary-button" onClick={() => setOpen(false)}>取消</button><button className="primary-button">保存</button></div></form></Modal>
  </div>;
}
