import { KeyRound, Mail, Send, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { useAuth } from "../contexts/AuthContext";
import { api, json } from "../lib/api";

interface SmtpResponse { smtp: null | { host: string; port: number; secure: boolean; username: string; from: string; recipients: string[]; hasPassword: boolean } }

export function SettingsPage() {
  const { user, refresh } = useAuth();
  const [smtp, setSmtp] = useState({ host: "", port: 587, secure: false, username: "", password: "", from: "", recipients: "" });
  const [passwords, setPasswords] = useState({ currentPassword: "", newPassword: "", confirm: "" });
  const [message, setMessage] = useState("");
  useEffect(() => { if (user?.role === "admin") void api<SmtpResponse>("/api/settings/smtp").then(({ smtp: value }) => { if (value) setSmtp({ ...value, password: "", recipients: value.recipients.join(", ") }); }); }, [user?.role]);
  function smtpPayload() { return { ...smtp, password: smtp.password || undefined, recipients: smtp.recipients.split(",").map((v) => v.trim()).filter(Boolean) }; }
  async function saveSmtp(event: React.FormEvent) { event.preventDefault(); await api("/api/settings/smtp", json("PUT", smtpPayload())); setMessage("邮件设置已保存"); }
  async function testMail() { await api("/api/settings/smtp", json("PUT", smtpPayload())); await api("/api/settings/smtp/test", json("POST")); setMessage("当前设置已保存，测试邮件已发送"); }
  async function changePassword(event: React.FormEvent) { event.preventDefault(); if (passwords.newPassword !== passwords.confirm) { setMessage("两次输入的新密码不一致"); return; } await api("/api/auth/change-password", json("POST", { currentPassword: passwords.currentPassword, newPassword: passwords.newPassword })); setPasswords({ currentPassword: "", newPassword: "", confirm: "" }); await refresh(); setMessage("密码已更新"); }
  return <div className="page-stack">{message && <div className="success-banner"><ShieldCheck size={17} />{message}<button onClick={() => setMessage("")}>关闭</button></div>}<section className="settings-section"><header><span className="settings-icon"><KeyRound size={19} /></span><div><h2>登录密码</h2><p>{user?.mustChangePassword ? "首次登录必须更换初始密码" : "更新当前账号的登录密码"}</p></div></header><form className="settings-form" onSubmit={changePassword}><label><span>当前密码</span><input type="password" autoComplete="current-password" value={passwords.currentPassword} onChange={(e) => setPasswords({ ...passwords, currentPassword: e.target.value })} required /></label><label><span>新密码</span><input type="password" autoComplete="new-password" minLength={10} value={passwords.newPassword} onChange={(e) => setPasswords({ ...passwords, newPassword: e.target.value })} required /></label><label><span>确认新密码</span><input type="password" autoComplete="new-password" minLength={10} value={passwords.confirm} onChange={(e) => setPasswords({ ...passwords, confirm: e.target.value })} required /></label><button className="primary-button">更新密码</button></form></section>{user?.role === "admin" && <section className="settings-section"><header><span className="settings-icon"><Mail size={19} /></span><div><h2>SMTP 邮件</h2><p>故障与恢复通知</p></div></header><form className="settings-form settings-form-wide" onSubmit={saveSmtp}><label><span>SMTP 主机</span><input value={smtp.host} onChange={(e) => setSmtp({ ...smtp, host: e.target.value })} required /></label><label><span>端口</span><input type="number" value={smtp.port} onChange={(e) => setSmtp({ ...smtp, port: Number(e.target.value) })} required /></label><label><span>用户名</span><input value={smtp.username} onChange={(e) => setSmtp({ ...smtp, username: e.target.value })} /></label><label><span>密码 / 授权码</span><input type="password" autoComplete="new-password" value={smtp.password} onChange={(e) => setSmtp({ ...smtp, password: e.target.value })} placeholder="留空保持现有密码" /></label><label><span>发件人</span><input value={smtp.from} onChange={(e) => setSmtp({ ...smtp, from: e.target.value })} required /></label><label><span>收件人（逗号分隔）</span><input value={smtp.recipients} onChange={(e) => setSmtp({ ...smtp, recipients: e.target.value })} required /></label><label className="switch-field"><input type="checkbox" checked={smtp.secure} onChange={(e) => setSmtp({ ...smtp, secure: e.target.checked })} /><span>使用隐式 TLS</span></label><div className="settings-actions"><button type="button" className="secondary-button" onClick={() => void testMail()}><Send size={16} />发送测试</button><button className="primary-button">保存邮件设置</button></div></form></section>}</div>;
}
