import { KeyRound, Pencil, Plus, ShieldCheck, Trash2, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Modal } from "../components/Modal";
import { EmptyState, Status } from "../components/Status";
import { api, json } from "../lib/api";
import { formatDate } from "../lib/format";
import type { User } from "../types";

export function UsersPage() {
  const [users, setUsers] = useState<User[]>([]);
  const [createOpen, setCreateOpen] = useState(false);
  const [editing, setEditing] = useState<User | null>(null);
  const [resetting, setResetting] = useState<User | null>(null);
  const [form, setForm] = useState({ username: "", displayName: "", password: "", role: "viewer" });
  const [password, setPassword] = useState("");
  async function load() { setUsers((await api<{ users: User[] }>("/api/users")).users); }
  useEffect(() => { void load(); }, []);
  async function create(event: React.FormEvent) { event.preventDefault(); await api("/api/users", json("POST", form)); setCreateOpen(false); setForm({ username: "", displayName: "", password: "", role: "viewer" }); await load(); }
  async function update(event: React.FormEvent) { event.preventDefault(); if (!editing) return; await api(`/api/users/${editing.id}`, json("PATCH", { displayName: editing.displayName, role: editing.role, disabled: editing.disabled })); setEditing(null); await load(); }
  async function reset(event: React.FormEvent) { event.preventDefault(); if (!resetting) return; await api(`/api/users/${resetting.id}/reset-password`, json("POST", { password })); setResetting(null); setPassword(""); await load(); }
  async function remove(item: User) { if (!window.confirm(`删除用户“${item.username}”？`)) return; await api(`/api/users/${item.id}`, json("DELETE")); await load(); }
  return <div className="page-stack">
    <div className="page-actions"><div><span className="eyebrow">ACCESS CONTROL</span><p className="page-summary">管理员维护账号，查看者拥有全局只读权限</p></div><button className="primary-button" onClick={() => setCreateOpen(true)}><Plus size={17} />添加用户</button></div>
    <section className="content-band">{users.length ? <div className="table-wrap"><table><thead><tr><th>用户</th><th>角色</th><th>状态</th><th>最近登录</th><th>创建时间</th><th /></tr></thead><tbody>{users.map((item) => <tr key={item.id}><td><div className="user-cell"><span className="avatar compact">{item.displayName.slice(0, 1).toUpperCase()}</span><div><strong>{item.displayName}</strong><span>@{item.username}</span></div></div></td><td><span className={`role-badge ${item.role}`}><ShieldCheck size={14} />{item.role === "admin" ? "管理员" : "查看者"}</span></td><td><Status good={!item.disabled} label={item.disabled ? "已禁用" : item.mustChangePassword ? "待改密" : "正常"} muted={Boolean(item.disabled)} /></td><td>{formatDate(item.lastLoginAt)}</td><td>{formatDate(item.createdAt)}</td><td><div className="row-actions"><button className="icon-button" onClick={() => setEditing({ ...item })} title="编辑"><Pencil size={16} /></button><button className="icon-button" onClick={() => { setResetting(item); setPassword(""); }} title="重置密码"><KeyRound size={16} /></button><button className="icon-button danger" onClick={() => void remove(item)} title="删除"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div> : <EmptyState title="暂无用户" detail="创建管理员或只读查看者账号" />}</section>
    <Modal open={createOpen} title="添加用户" onClose={() => setCreateOpen(false)}><form className="form-grid" onSubmit={create}><label><span>用户名</span><input value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} pattern="[a-zA-Z0-9._-]{2,64}" required /></label><label><span>显示名称</span><input value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} required /></label><label className="field-span"><span>初始密码</span><input type="password" autoComplete="new-password" minLength={10} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required /></label><label className="field-span"><span>角色</span><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="viewer">查看者</option><option value="admin">管理员</option></select></label><div className="modal-actions field-span"><button type="button" className="secondary-button" onClick={() => setCreateOpen(false)}>取消</button><button className="primary-button">创建</button></div></form></Modal>
    <Modal open={Boolean(editing)} title="编辑用户" onClose={() => setEditing(null)}>{editing && <form className="form-grid" onSubmit={update}><label className="field-span"><span>显示名称</span><input value={editing.displayName} onChange={(e) => setEditing({ ...editing, displayName: e.target.value })} required /></label><label><span>角色</span><select value={editing.role} disabled={editing.username.toLowerCase() === "root"} onChange={(e) => setEditing({ ...editing, role: e.target.value as User["role"] })}><option value="viewer">查看者</option><option value="admin">管理员</option></select></label><label className="switch-field"><input type="checkbox" checked={!editing.disabled} disabled={editing.username.toLowerCase() === "root"} onChange={(e) => setEditing({ ...editing, disabled: !e.target.checked })} /><span>允许登录</span></label><div className="modal-actions field-span"><button type="button" className="secondary-button" onClick={() => setEditing(null)}>取消</button><button className="primary-button">保存</button></div></form>}</Modal>
    <Modal open={Boolean(resetting)} title={`重置 ${resetting?.username ?? ""} 的密码`} onClose={() => setResetting(null)}>{resetting && <form className="form-grid" onSubmit={reset}><div className="notice field-span"><UserRound size={17} /><span>无需旧密码。保存后该用户的现有会话将全部退出。</span></div><label className="field-span"><span>新密码</span><input type="password" autoComplete="new-password" minLength={10} value={password} onChange={(e) => setPassword(e.target.value)} required autoFocus /></label><div className="modal-actions field-span"><button type="button" className="secondary-button" onClick={() => setResetting(null)}>取消</button><button className="primary-button">覆盖密码</button></div></form>}</Modal>
  </div>;
}
